bit_posts/urls.py
from django.urls import path
from .views import post_views 


app_name = 'bit_posts'

urlpatterns = [
    path('', post_views.PostListView.as_view(), name='post-list-create'),
    path('api/posts/', post_views.PostCreateAPIView.as_view(), name='api-post-create'),  
    path('post/<int:post_id>/create-comment/', post_views.create_comment, name='create-comment'),
    path('delete-comment/<int:comment_id>/', post_views.delete_comment, name='delete-comment'),
    path('edit-comment/<int:pk>/edit/', post_views.UpdateComment.as_view(), name='edit-comment'),  
    path('api/post/<int:post_id>/upvote/', post_views.upvote_post, name='upvote-post'),
    path('post-update/<int:pk>/', post_views.UpdatePost.as_view(), name='update-post'),
    path('post-delete/<int:pk>/', post_views.DeletePost.as_view(), name='delete-post'),
    path('post/<int:parent_comment_id>/reply/', post_views.create_subcomment, name='reply-comment'),
    path('subcomment/<int:subcomment_id>/delete/', post_views.delete_subcomment, name='delete-subcomment'),
    path('subcomment/<int:pk>/update/', post_views.UpdateSubcomment.as_view(), name='update-subcomment'),
    path('api/get-post-by-id/', post_views.get_post_by_id, name='get-post-by-id'),
    path('retrieve/', post_views.retrieve_view, name='find-by-id'), 
]




bit_users/urls.py
# appname/urls.py
from django.urls import path
from . import views

app_name = 'bit_users' 
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('home/', views.HomePageView.as_view(), name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

breddit_django/urls.py
from django.urls import include, path
from django.contrib import admin
from breddit_django import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from bit_posts.views import post_views 


urlpatterns = [
    path('',views.HomePage.as_view(),name='home'),
    path('posts/', include('bit_posts.urls')),
    path('admin/', admin.site.urls), 
    path('users/', include('bit_users.urls')),
    path('contact/', views.ContactPage.as_view(), name='contact'),
    path('privacy/', views.PrivacyPage.as_view(), name='privacy'), 
    path('post/<int:post_id>/create-comment/', post_views.create_comment, name='create-comment'),
]


urlpatterns += staticfiles_urlpatterns()

bit_posts/models/post.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

class Post(models.Model):
    title = models.CharField(
        _('Title'),
        max_length=255,
    )

    content = models.TextField(
        _('Text')
    )

    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    upvotes = models.ManyToManyField(
        get_user_model(),
        related_name='upvoted_posts',
        blank=True,
    )

    def upvote(self, user):
        """
        Upvote the post by a user.
        """
        if user not in self.upvotes.all():
            self.upvotes.add(user)
            self.save()

    def remove_upvote(self, user):
        """
        Remove upvote from the post by a user.
        """
        if user in self.upvotes.all():
            self.upvotes.remove(user)
            self.save()
            
            
            
#model for comments
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    text = models.TextField()
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    is_reply = models.BooleanField(default=False)
    
    upvotes = models.ManyToManyField(
        get_user_model(),
        related_name='upvoted_comments',
        blank=True,
    )

    def upvote(self, user):
        """
        Upvote the comment by a user.
        """
        if user not in self.upvotes.all():
            self.upvotes.add(user)
            self.save()

    def remove_upvote(self, user):
        """
        Remove upvote from the comment by a user.
        """
        if user in self.upvotes.all():
            self.upvotes.remove(user)
            self.save()

    def __str__(self):
        return f"Comment by {self.user.username} on {self.post.title}"
    
    
    
#nested sub comments/replys for comments
class SubComment(models.Model):
    parent_comment = models.ForeignKey(
        'Comment',
        on_delete=models.CASCADE,
        related_name='subcomments',
    )
    
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    text = models.TextField(_('Text'))
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    is_reply = models.BooleanField(default=True)  

    def __str__(self):
        return f"SubComment by {self.user.username} on {self.parent_comment.post.title}"

bit_posts/forms/forms.py
from django import forms
from bit_posts.models.post import Comment,SubComment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class ReplyToCommentForm(forms.ModelForm):
    class Meta:
        model = SubComment  #Child model for Comment Model
        fields = ['text']

bit_posts/views/post_views.py
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework import generics, status
from rest_framework import permissions
from django.http import JsonResponse
from django.http import HttpResponseRedirect
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from bit_posts.models.post import Comment, Post, SubComment
from django.contrib import messages
from bit_posts.forms.forms import CommentForm, ReplyToCommentForm  
from bit_posts.serializers import post_serializers
from django.contrib import messages
from django.urls import reverse_lazy, reverse 
from django.db.models import Count

#  #  # POSTS #  #  #

# Posts API
class PostListView(generics.ListCreateAPIView):
    serializer_class = post_serializers.PostSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    queryset = Post.objects.all().order_by('-created_at')

    def list(self, request, *args, **kwargs):
        filter_type = request.GET.get('filter', 'recent')  

        if filter_type == 'likes':
            queryset = self.get_queryset().annotate(upvotes_count=Count('upvotes')).order_by('-upvotes_count', '-created_at')
        elif filter_type == 'comments':
            queryset = self.get_queryset().annotate(comments_count=Count('comments')).order_by('-comments_count', '-created_at')
        else:
            queryset = self.get_queryset().order_by('-created_at')

        return render(request, 'bit_posts/posts.html', {'object_list': queryset})


class PostCreateAPIView(generics.CreateAPIView):
    serializer_class = post_serializers.PostSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    
    
# Edit Posts
class UpdatePost(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'bit_posts/edit_post.html'  # Create an edit_post.html template
    fields = [ 'title','content']  
    
    def get_success_url(self):
        return reverse('bit_posts:post-list-create')
    

# Delete Posts
class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'bit_posts/delete_post.html'  
    success_url = reverse_lazy('bit_posts:post-list-create')  
    
    

# API Finds Post By ID
@api_view(['POST'])
def get_post_by_id(request):
    try:
        post_id = request.data.get('post_id')
        post = Post.objects.get(id=post_id)
        serializer = post_serializers.PostSerializer(post)
        return Response(serializer.data)
    except Post.DoesNotExist:
        return Response({'error': 'Post not found'}, status=status.HTTP_404_NOT_FOUND)
    except Exception as e:
        return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    
def retrieve_view(request):
    return render(request, 'bit_posts/find_by_id.html')
    




#  #  # COMMENTS #  #  #

# Create Comment
def create_comment(request, post_id, comment_id=None):
    post = get_object_or_404(Post, pk=post_id)

    if not request.user.is_authenticated:
        # If the user is not logged in, add an error message and redirect them
        messages.error(request, 'You must be logged in to comment.')
        return redirect('bit_users:login')  

    parent_comment = None

    if comment_id:
        parent_comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.parent_comment = parent_comment  
            comment.save()
            return redirect('create-comment', post_id=post_id)  
        else:
          
            messages.error(request, 'There was an error with your comment. Please correct it.')

    else:
        form = CommentForm()

    comments = Comment.objects.filter(post=post, parent_comment=None).order_by('-created_at')
    # Filter only top-level comments for the post 
    
    context = {
        'form': form,
        'post': post,
        'post_id': post_id,
        'comments': comments,
    }

    return render(request, 'bit_posts/create_comment.html', context)



# Delete Comment
def delete_comment(request, comment_id):
    try:
        comment = Comment.objects.get(pk=comment_id)
        
        # Check if the user is authorized to delete the comment

        comment.delete()
        messages.success(request, 'Comment deleted successfully.')
    except Comment.DoesNotExist:
        messages.success(request, 'Comment deleted.')
    except Exception as e:
        messages.error(request, f'Error deleting comment: {str(e)}')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# Edit Comments 
class UpdateComment(UpdateView):
    model = Comment
    template_name = 'bit_posts/edit_comment.html'  
    fields = ['text']  
    
    def get_success_url(self):
       
        return reverse('bit_posts:create-comment', kwargs={'post_id': self.object.post.pk})



#  #  # Upvote API #  #  #

# Upvote Api
@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def upvote_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user

    if post.upvotes.filter(id=user.id).exists():
      
        post.upvotes.remove(user)
        message = 'Upvote removed successfully.'
        liked = False  
    else:
       
        post.upvotes.add(user)
        message = 'Upvoted successfully.'
        liked = True  

    post.save()

    new_like_count = post.upvotes.count

    referring_page = request.META.get('HTTP_REFERER')
    return HttpResponseRedirect(referring_page)





#  #  # REPLIES/SUBCOMMENTS FOR COMMENTS #  #  #


# Create Replies
def create_subcomment(request, parent_comment_id):
    parent_comment = get_object_or_404(Comment, id=parent_comment_id)

    if request.method == 'POST':
        form = ReplyToCommentForm(request.POST)
        if form.is_valid():
            subcomment = form.save(commit=False)
            subcomment.user = request.user
            subcomment.parent_comment = parent_comment
            subcomment.post = parent_comment.post 
            subcomment.is_reply = True  
            subcomment.save()
            
            return redirect('bit_posts:create-comment', post_id=parent_comment.post.id)

    subcomments = SubComment.objects.filter(parent_comment=parent_comment).order_by('-created_at')  

    form = ReplyToCommentForm()
    
    return render(request, 'bit_posts/reply_comment.html', {'form': form, 'parent_comment': parent_comment, 'subcomments': subcomments})
    

# Delete Replies 
def delete_subcomment(request, subcomment_id):
    try:
        subcomment = SubComment.objects.get(pk=subcomment_id)
        
        subcomment.delete()
        messages.success(request, 'Subcomment deleted successfully.')
    except SubComment.DoesNotExist:
        messages.success(request, 'Subcomment deleted.')
    except Exception as e:
        messages.error(request, f'Error deleting subcomment: {str(e)}')

  
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# Update Replies
class UpdateSubcomment(UpdateView):
    model = SubComment  
    template_name = 'bit_posts/edit_subcomment.html'  
    fields = ['text']  

    def get_success_url(self):
        return reverse('bit_posts:create-comment', kwargs={'post_id': self.object.parent_comment.post.pk})
    





bit_posts/templates/bit_posts/create_comment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <script src="{% static 'breddit/css/bit_posts/master.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'breddit/css/bit_posts/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>
    <div class="back-button-container">
        <a class="back-button" href="{% url 'bit_posts:post-list-create' %}">
            <i class="fas fa-arrow-left"></i> Back
        </a>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Breddit</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Create Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:find-by-id' %}">Find by ID</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:signup' %}">Signup</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container mt-5 mt-4">
        
    <h4 style="margin-left: 17px;">Breddit Post</h4>
        
{% if post %}
<div class="post">
    <h2 class="post-title">{{ post.title }}</h2>
    <p class="post-content">{{ post.content }}</p>
    <p class="post-author">Author: {{ post.user.username }}</p>
    <button class="like-button" data-post-id="{{ post.id }}">
        {% if request.user in post.upvotes.all %}<i class="fas fa-thumbs-down"></i> Unlike{% else %}<i class="fas fa-thumbs-up"></i> Like{% endif %}
    </button>
    <span class="likes-count">{{ post.upvotes.count }}</span> likes
</div>
{% endif %}

<!-- Comment input form -->
{% if user.is_authenticated %}
<div class="comment-form mt-9">
    <h1>Add a Comment</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control comment-input" name="text" rows="5" placeholder="Write your comment here"></textarea>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Submit Comment</button>
    </form>
</div>
{% endif %}


<!-- Error messages display -->
{% if messages %}
<l class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}



<h1 class="mt-4" style="margin-left: 17px;">Comments</h1>
<p style="margin-left: 17px;"> These are comments for breddit ID {{ post_id }}</p>


<!-- Display top-level comments -->
<div class="comments-section">
    {% for comment in comments %}
    <div class="comment">
        <div class="comment-header">
            <span class="comment-author">{{ comment.user.username }}</span>
            <span class="comment-timestamp">{{ comment.created_at }}</span>
        </div>
        <div class="comment-content">
            <p>{{ comment.text }}</p>
        </div>
        <div class="comment-actions">
            {% if comment.user == request.user %}
            <div style="display: flex; align-items: center; justify-content: flex-start;">
                <!-- Edit Button Top-Level Comment -->
                <a class="btn btn-primary btn-sm edit-comment-button" style="text-decoration: none;" href="{% url 'bit_posts:edit-comment' comment.id %}">Edit</a>

                <!-- Delete Button for Top-Level Comment -->
                <form method="post" action="{% url 'bit_posts:delete-comment' comment.id %}">
                    {% csrf_token %}
                    <button class="btn btn-danger btn-sm delete-comment-button" type="submit">Delete</button>
                </form>
            </div>
            {% endif %}
        </div>
        

        <!-- Display Reply Button for each comment -->
        <button class="open-close-replies-button" style="margin-right: 418px;">
            <i class="fas fa-chevron-down"></i> Open Replies
        </button>
        <a href="{% url 'bit_posts:reply-comment' comment.id %}" class="comment-reply-action" style="margin-right: 500px;">
            <i class="fas fa-reply"></i> Reply To Comment
        </a>
        

        <!-- Display replies to this comment if any -->
        <ul class="replies" style="display:none;">
            {% for reply in comment.subcomments.all|dictsortreversed:"created_at" %}
            <li class="reply">
                <div class="comment-header">
                    <span class="comment-author">{{ reply.user.username }}</span>
                    <span class="comment-timestamp">{{ reply.created_at }}</span>
                </div>
                <div class="comment-content">
                    <p>{{ reply.text }}</p>
                </div>
                <div class="comment-actions">
                    {% if reply.user == request.user %}
                    <div style="display: flex; align-items: center; justify-content: flex-start;">
                        <!-- Edit Button for Reply  -->
                        <a class="btn btn-primary btn-sm edit-comment-button" href="{% url 'bit_posts:update-subcomment' reply.id %}">Edit</a>
        
                        <!-- Delete Button for Reply  -->
                        <form method="post" action="{% url 'bit_posts:delete-subcomment' reply.id %}">
                            {% csrf_token %}
                            <button class="btn btn-danger btn-sm delete-comment-button" type="submit">Delete</button>
                        </form>
                    </div>
                    {% endif %}
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
</div>



<!-- Display success and error messages -->
{% if messages %}
<div class="alert">
    {% for message in messages %}
        <p {% if message.tags %}class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}
</div>

<style>
    .alert {
        color: green;
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Initialize Bootstrap components
        $(document).ready(function () {
            // Initialize Bootstrap Navbar
            $('.navbar-toggler').click(function () {
                $('#navbarNav').toggleClass('show');
            });
        });
    </script>

</body>
</html>

bit_posts/templates/bit_posts/edit_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    <link rel="stylesheet" type="text/css" href="{% static 'breddit/css/bit_posts/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>

<body>
    <div class="back-button-container">
        <a class="back-button" href="{% url 'bit_posts:post-list-create' %}">
            <i class="fas fa-arrow-left"></i> Back
        </a>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Breddit</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Create Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:find-by-id' %}">Find by ID</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:signup' %}">Signup</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container mt-5 mt-4">
      
<!-- Display the found post -->
{% if post %}
<div class="post">
    <h2 class="post-title">{{ post.title }}</h2>
    <p class="post-content">{{ post.content }}</p>
    <p class="post-author">Author: {{ post.user.username }}</p>
    <button class="like-button" data-post-id="{{ post.id }}">
        {% if request.user in post.upvotes.all %}<i class="fas fa-thumbs-down"></i> Unlike{% else %}<i class="fas fa-thumbs-up"></i> Like{% endif %}
    </button>
    <span class="likes-count">{{ post.upvotes.count }}</span> likes
</div>
{% endif %}

<!-- Comment input form -->
<div class="comment-form mt-9">
    <h1>Edit Your Post</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title</label>
            <input type="text" class="form-control" id="id_title" name="title" value="{{ post.title }}">
        </div>
        <div class="form-group">
            <label for="id_content">Content</label>
            <textarea class="form-control comment-input" id="id_content" name="content" rows="5" placeholder="Re-write your post content here!">{{ post.content }}</textarea>
        </div>
        
        <button class="btn btn-primary mt-2" type="submit">Save</button>
    </form>
</div>


<!-- Error messages display -->
{% if messages %}
<l class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Initialize Bootstrap components
        $(document).ready(function () {
            // Initialize Bootstrap Navbar
            $('.navbar-toggler').click(function () {
                $('#navbarNav').toggleClass('show');
            });
        });
    </script>

</body>
</html>

bit_posts/templates/bit_posts/reply_comment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <script src="{% static 'breddit/css/bit_posts/master.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'breddit/css/bit_posts/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>

<body>
    <div class="back-button-container">
        <a class="back-button" href="javascript:history.back()">
            <i class="fas fa-arrow-left"></i> Back
        </a>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Breddit</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Create Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:find-by-id' %}">Find by ID</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_posts:post-list-create' %}">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bit_users:signup' %}">Signup</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container mt-5 mt-4">
        
        
{% if post %}
<div class="post">
    <h2 class="post-title">{{ post.title }}</h2>
    <p class="post-content">{{ post.content }}</p>
    <p class="post-author">Author: {{ post.user.username }}</p>
    <button class="like-button" data-post-id="{{ post.id }}">
        {% if request.user in post.upvotes.all %}<i class="fas fa-thumbs-down"></i> Unlike{% else %}<i class="fas fa-thumbs-up"></i> Like{% endif %}
    </button>
    <span class="likes-count">{{ post.upvotes.count }}</span> likes
</div>
{% endif %}

<!-- Comment input form -->
{% if user.is_authenticated %}
<div class="comment-form mt-9">
    <h1>Add a Reply</h1>
    <form method="post" action="{% url 'bit_posts:reply-comment' parent_comment.id %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_text">Text:</label>
           <textarea class="form-control comment-input" name="text" rows="5" placeholder="Write your reply here"></textarea>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Submit Reply</button>
    </form>
</div>
{% endif %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Initialize Bootstrap components
        $(document).ready(function () {
            // Initialize Bootstrap Navbar
            $('.navbar-toggler').click(function () {
                $('#navbarNav').toggleClass('show');
            });
        });
    </script>
</body>
</html>